import { useState } from "react";
import { Plus, ArrowLeft, Target, ListTodo, CheckCircle2, BookOpen } from "lucide-react";
import { useApp } from "../hooks/useApp";
import DailyTaskCard from "../components/DailyTaskCard";
import SideQuestCard from "../components/SideQuestCard";
import CompleteTaskModal from "../components/CompleteTaskModal";
import CreateDailyTaskModal from "../components/CreateDailyTaskModal";
import CreateSideQuestModal from "../components/CreateSideQuestModal";
import CreateQuestBookModal from "../components/CreateQuestBookModal";
import CreateQuestLineModal from "../components/CreateQuestLineModal";
import CreateQuestStageModal from "../components/CreateQuestStageModal";
import CreateQuestBookTaskModal from "../components/CreateQuestBookTaskModal";
import EditQuestBookModal from "../components/EditQuestBookModal";
import EditDailyTaskModal from "../components/EditDailyTaskModal";
import EditSideQuestModal from "../components/EditSideQuestModal";
import NpcAgentPanel from "../components/NpcAgentPanel";
import MaroChatModal from "../components/MaroChatModal";
import { WireframeBox } from "../components/vintage";
import { NPCS } from "../data/npcs";
import type { CompletionContext, Mood, EnergyLevel, QuestBook, DailyTask, SideQuest } from "../types";
import { today } from "../utils/date";

function CB({ onClick, children, shaded }: { onClick?: () => void; children: any; shaded?: boolean }) {
  return <div className={`chamfer-btn h-7 flex-shrink-0 ${shaded?"chamfer-btn-shaded":""}`} onClick={onClick}><div className="chamfer-outer"><div className="chamfer-gap"><div className="chamfer-inner"><div className="chamfer-core px-3">{children}</div></div></div></div></div>;
}

export default function TasksPage() {
  const { state, completeQuestStage, completeQuestBookTask, completeDailyTask, completeSideQuest,
    addJournal, addQuestBook, addQuestLine, addQuestStage, addQuestBookTask, addDailyTask, addSideQuest, toggleDailyActive,
    updateQuestBook, updateDailyTask, updateSideQuest,
    archiveQuestBook, archiveDailyTask, archiveSideQuest, deleteQuestBook, deleteDailyTask, deleteSideQuest } = useApp();
  const [sel,setSel]=useState<string|null>(null);const[cc,setCc]=useState<CompletionContext|null>(null);
  const [cm,setCm]=useState<"book"|"daily"|"side"|null>(null);const[sal,setSal]=useState(false);const[sat,setSat]=useState(false);
  const [asl,setAsl]=useState<string|null>(null);const[eb,setEb]=useState<QuestBook|null>(null);
  const [ed,setEd]=useState<DailyTask|null>(null);const[es,setEs]=useState<SideQuest|null>(null);const[smc,setSmc]=useState(false);
  const hsc=(b:string,l:string,s:string)=>{const r=completeQuestStage(b,l,s);if(r)setCc(r)};const htc=(b:string,t:string)=>{const r=completeQuestBookTask(b,t);if(r)setCc(r)};
  const hdc=(id:string)=>{const r=completeDailyTask(id);if(r)setCc(r)};const hsc2=(id:string)=>{const r=completeSideQuest(id);if(r)setCc(r)};
  const hsj=(c:string,m:Mood,e:EnergyLevel)=>{if(cc&&c.trim())addJournal({date:today(),taskId:cc.itemId,mood:m,energy:e,content:c.trim(),tags:[]});setCc(null)};
  const ad=state.dailyTasks.filter(d=>d.active&&!d.archived);const ps=state.sideQuests.filter(s=>!s.completed&&!s.archived);

  if(sel){const qb=state.questBooks.find(q=>q.id===sel);if(!qb)return null;const t=qb.questLines.reduce((a,l)=>a+l.stages.length,0)+qb.directTasks.length;const d=qb.questLines.reduce((a,l)=>a+l.stages.filter(s=>s.completed).length,0)+qb.directTasks.filter(t=>t.completed).length;const p=t>0?Math.round((d/t)*100):0;
    return <div className="space-y-6 animate-fade pb-24">
      <button onClick={()=>setSel(null)} className="flex items-center gap-1.5 text-[11px] font-bold text-[#4A3B2C]/40 uppercase tracking-widest hover:text-[#4A3B2C]"><ArrowLeft size={14}/>返回</button>
      <div className="text-center space-y-2"><p className="text-[#8B3A3A] font-bold text-xs tracking-widest uppercase">{qb.status==="active"?"进行中":qb.status==="paused"?"已暂停":"已完成"}</p><div className="flex items-center justify-center gap-2"><BookOpen size={18}/><h2 className="text-2xl font-black text-[#4A3B2C] tracking-tight serif cursor-pointer" onClick={()=>setEb(qb)}>{qb.title}</h2></div><p className="text-[12px] text-[#4A3B2C]/50 font-medium leading-relaxed serif">{qb.description}</p></div>
      <WireframeBox innerClassName="p-3"><div className="flex justify-between text-[9px] font-bold text-[#4A3B2C]/30 uppercase tracking-widest mb-1 px-1"><span>进度</span><span>{d}/{t}</span></div><div className="progress-track"><div className="progress-fill" style={{width:p+"%"}}/></div></WireframeBox>
      {qb.questLines.map(ql=><WireframeBox key={ql.id} innerClassName=""><div className="h-7 border-b-[0.5px] border-[#4A3B2C]/15 flex items-center justify-between px-3"><div className="flex items-center gap-2"><div className="w-1 h-4 bg-[#4A3B2C]"/><Target size={13}/><h3 className="text-[10px] font-black text-[#4A3B2C] uppercase tracking-widest">{ql.title||"任务线"}</h3><span className="text-[9px] font-bold text-[#4A3B2C]/25 bg-[#E3D4BB] px-2 py-0.5 border border-[#4A3B2C]/10">{ql.stages.filter(s=>s.completed).length}/{ql.stages.length}</span></div><button onClick={()=>setAsl(ql.id)} className="text-[10px] font-bold text-[#4A3B2C]/30 hover:text-[#4A3B2C]"><Plus size={12}/>添加阶段</button></div><div className="p-3 space-y-1.5">{ql.stages.map((s,i)=>{const ic=!s.completed&&(i===0||ql.stages[i-1].completed);const fut=!s.completed&&!ic;return <WireframeBox key={s.id} shaded innerClassName={`p-3 flex items-center justify-between gap-3 ${ic?"shadow-[2px_2px_0px_rgba(74,59,44,0.3)]":""}`}><div className="flex-1 min-w-0"><span className="text-[9px] font-bold text-[#4A3B2C]/25 uppercase tracking-widest">阶段 {i+1}</span><h4 className={`text-[12px] font-bold ${s.completed?"text-[#4A3B2C]/30 line-through":"text-[#4A3B2C]"}`}>{s.title}</h4>{s.description&&<p className="text-[9px] text-[#4A3B2C]/35 mt-0.5">{s.description}</p>}</div>{ic&&<CB onClick={()=>hsc(qb.id,ql.id,s.id)}><CheckCircle2 size={11}/><span className="text-[9px] font-bold ml-1">完成</span></CB>}{s.completed&&<CheckCircle2 size={14} className="text-[#4A3B2C]/40 flex-shrink-0"/>}{fut&&<div className="w-6 h-6 border border-[#4A3B2C]/15 flex items-center justify-center flex-shrink-0"><div className="w-1.5 h-1.5 border border-[#4A3B2C]/20"/></div>}</WireframeBox>})}</div></WireframeBox>)}
      <button onClick={()=>setSal(true)} className="w-full py-2.5 border-[1.5px] border-dashed border-[#4A3B2C]/20 text-[10px] font-bold text-[#4A3B2C]/30 hover:text-[#4A3B2C] hover:border-[#4A3B2C]/40">+ 添加任务线</button>
      {qb.directTasks.length>0&&<WireframeBox innerClassName=""><div className="h-7 border-b-[0.5px] border-[#4A3B2C]/15 flex items-center justify-between px-3"><div className="flex items-center gap-2"><div className="w-1 h-4 bg-[#8B3A3A]"/><CheckCircle2 size={13}/><h3 className="text-[10px] font-black text-[#4A3B2C] uppercase tracking-widest">直接任务</h3><span className="text-[9px] font-bold text-[#4A3B2C]/25 bg-[#E3D4BB] px-2 py-0.5 border border-[#4A3B2C]/10">{qb.directTasks.filter(t=>t.completed).length}/{qb.directTasks.length}</span></div><button onClick={()=>setSat(true)} className="text-[10px] font-bold text-[#4A3B2C]/30 hover:text-[#4A3B2C]"><Plus size={12}/>添加</button></div><div className="p-3 space-y-1.5">{qb.directTasks.map(t=><WireframeBox key={t.id} shaded innerClassName="p-3 flex items-center justify-between gap-3"><div className="flex-1 min-w-0"><h4 className={`text-[12px] font-bold ${t.completed?"text-[#4A3B2C]/30 line-through":"text-[#4A3B2C]"}`}>{t.title}</h4></div>{!t.completed?<CB onClick={()=>htc(qb.id,t.id)}><CheckCircle2 size={11}/><span className="text-[9px] font-bold ml-1">完成</span></CB>:<CheckCircle2 size={14} className="text-[#4A3B2C]/40 flex-shrink-0"/>}</WireframeBox>)}</div></WireframeBox>}
      {cc&&<CompleteTaskModal ctx={cc} onClose={()=>setCc(null)} onSaveJournal={hsj}/>}{sal&&<CreateQuestLineModal bookId={qb.id} onClose={()=>setSal(false)} onCreate={addQuestLine}/>}{asl&&<CreateQuestStageModal bookId={qb.id} lineId={asl} onClose={()=>setAsl(null)} onCreate={addQuestStage}/>}{sat&&<CreateQuestBookTaskModal bookId={qb.id} onClose={()=>setSat(false)} onCreate={addQuestBookTask}/>}{eb&&<EditQuestBookModal questBook={eb} onClose={()=>setEb(null)} onUpdate={updateQuestBook} onArchive={archiveQuestBook} onDelete={deleteQuestBook}/>}{ed&&<EditDailyTaskModal task={ed} onClose={()=>setEd(null)} onUpdate={updateDailyTask} onArchive={archiveDailyTask} onDelete={deleteDailyTask}/>}{es&&<EditSideQuestModal quest={es} onClose={()=>setEs(null)} onUpdate={updateSideQuest} onArchive={archiveSideQuest} onDelete={deleteSideQuest}/>}
    </div>}

  return <div className="space-y-6 pb-24 animate-in"><div className="pt-2"><p className="text-[#8B3A3A] font-bold text-xs tracking-widest uppercase mb-1">任务书</p><h2 className="text-2xl font-black text-[#4A3B2C] tracking-tight serif">全部任务</h2></div>
    <NpcAgentPanel npc={NPCS.maro} message="欢迎来到冒险公会。告诉我你想生成什么类型的任务，我来帮你规划。" actionLabel="让 Maro 生成任务" onAction={()=>setSmc(true)}/>
    <P icon={<BookOpen size={15}/>} t="任务书" bar="bg-[#4A3B2C]" n={state.questBooks.filter(q=>!q.archived).length} onAdd={()=>setCm("book")}>{state.questBooks.filter(q=>!q.archived).length===0?<E>还没有任务书。</E>:state.questBooks.filter(q=>!q.archived).map(qb=>{const t=qb.questLines.reduce((a,l)=>a+l.stages.length,0)+qb.directTasks.length;const d=qb.questLines.reduce((a,l)=>a+l.stages.filter(s=>s.completed).length,0)+qb.directTasks.filter(t=>t.completed).length;const p=t>0?Math.round((d/t)*100):0;return <WireframeBox key={qb.id} shaded innerClassName="p-3 cursor-pointer" className="cursor-pointer hover:shadow-[3px_3px_0px_rgba(74,59,44,0.15)] transition-all" onClick={()=>setSel(qb.id)}><div className="flex items-center gap-3"><div className="flex-1 min-w-0"><h4 className="text-[13px] font-black text-[#4A3B2C]">{qb.title}</h4><div className="flex items-center gap-2 mt-1"><span className={`text-[9px] font-bold uppercase tracking-widest ${qb.status==="active"?"text-[#8B3A3A]":"text-[#4A3B2C]/30"}`}>{qb.status==="active"?"进行中":qb.status==="paused"?"暂停":"完成"}</span><span className="text-[9px] text-[#4A3B2C]/25">{qb.questLines.length}线·{d}/{t}</span></div></div><div className="text-right"><span className="text-[11px] font-black text-[#4A3B2C] tabular-nums">{p}%</span></div></div>{t>0&&<div className="mt-2 progress-track"><div className="progress-fill" style={{width:p+"%"}}/></div>}</WireframeBox>})}</P>
    <P icon={<ListTodo size={15}/>} t="日常" bar="bg-[#8B3A3A]" n={ad.length} onAdd={()=>setCm("daily")}>{state.dailyTasks.filter(d=>!d.archived).length===0?<E>还没有日常任务。</E>:state.dailyTasks.filter(d=>!d.archived).map(dt=><DailyTaskCard key={dt.id} task={dt} onComplete={hdc} onToggle={toggleDailyActive} onEdit={setEd}/>)}</P>
    <P icon={<CheckCircle2 size={15}/>} t="支线" bar="bg-[#3A5A3A]" n={ps.length} onAdd={()=>setCm("side")}>{state.sideQuests.filter(s=>!s.archived).length===0?<E>还没有支线任务。</E>:state.sideQuests.filter(s=>!s.archived).map(sq=><SideQuestCard key={sq.id} quest={sq} onComplete={hsc2} onEdit={setEs}/>)}</P>
    <div className="chamfer-btn w-12 h-12 fixed bottom-20 md:bottom-6 right-4 md:right-6 z-40" onClick={()=>setCm("book")}><div className="chamfer-outer"><div className="chamfer-gap"><div className="chamfer-inner"><div className="chamfer-core"><Plus size={20} strokeWidth={2.5}/></div></div></div></div></div>
    {cc&&<CompleteTaskModal ctx={cc} onClose={()=>setCc(null)} onSaveJournal={hsj}/>}{cm==="book"&&<CreateQuestBookModal onClose={()=>setCm(null)} onCreate={addQuestBook}/>}{cm==="daily"&&<CreateDailyTaskModal onClose={()=>setCm(null)} onCreate={addDailyTask}/>}{cm==="side"&&<CreateSideQuestModal onClose={()=>setCm(null)} onCreate={addSideQuest}/>}{eb&&<EditQuestBookModal questBook={eb} onClose={()=>setEb(null)} onUpdate={updateQuestBook} onArchive={archiveQuestBook} onDelete={deleteQuestBook}/>}{ed&&<EditDailyTaskModal task={ed} onClose={()=>setEd(null)} onUpdate={updateDailyTask} onArchive={archiveDailyTask} onDelete={deleteDailyTask}/>}{es&&<EditSideQuestModal quest={es} onClose={()=>setEs(null)} onUpdate={updateSideQuest} onArchive={archiveSideQuest} onDelete={deleteSideQuest}/>}{smc&&<MaroChatModal onClose={()=>setSmc(false)}/>}
  </div>;
}
function P({icon,t,bar,n,onAdd,children}:{icon:any;t:string;bar:string;n:number;onAdd:()=>void;children:any}){return<WireframeBox innerClassName=""><div className="h-7 border-b-[0.5px] border-[#4A3B2C]/15 flex items-center justify-between px-3"><div className="flex items-center gap-2"><div className={`w-1 h-4 ${bar}`}/>{icon}<h3 className="text-[10px] font-black text-[#4A3B2C] uppercase tracking-widest">{t}</h3><span className="text-[9px] font-bold text-[#4A3B2C]/25 bg-[#E3D4BB] px-2 py-0.5 border border-[#4A3B2C]/10">{n}</span></div><button onClick={onAdd} className="text-[10px] font-bold text-[#4A3B2C]/30 hover:text-[#4A3B2C] flex items-center gap-1"><Plus size={12}/>添加</button></div><div className="p-3 space-y-2">{children}</div></WireframeBox>;}
function E({children}:{children:any}){return<div className="text-center py-6"><p className="text-[10px] font-medium text-[#4A3B2C]/25">{children}</p></div>}
